version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root-Verzeichnis des Projekts
    schedule:
      interval: "monthly"
      time: "06:00"
      day: "15"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
